ALTER TABLE links ALTER COLUMN og_image SET NOT NULL;
ALTER TABLE links ALTER COLUMN og_image SET DEFAULT '';
ALTER TABLE links ALTER COLUMN description SET NOT NULL;
ALTER TABLE links ALTER COLUMN description SET DEFAULT '';
ALTER TABLE links ALTER COLUMN title SET NOT NULL;
ALTER TABLE links ALTER COLUMN title SET DEFAULT '';

ALTER TABLE links ALTER COLUMN created_at TYPE TIMESTAMP;
ALTER TABLE links ALTER COLUMN project_id TYPE INT;
ALTER TABLE links ALTER COLUMN id DROP IDENTITY;
ALTER TABLE links ALTER COLUMN id TYPE INT;

ALTER TABLE projects ALTER COLUMN created_at TYPE TIMESTAMP;
ALTER TABLE projects ALTER COLUMN id DROP IDENTITY;
ALTER TABLE projects ALTER COLUMN id TYPE INT;
