-- projects: SERIAL → IDENTITY, TIMESTAMP → TIMESTAMPTZ
ALTER TABLE projects ALTER COLUMN id DROP DEFAULT;
ALTER TABLE projects ALTER COLUMN id TYPE BIGINT;
ALTER TABLE projects ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE projects ALTER COLUMN created_at TYPE TIMESTAMPTZ;

-- links: SERIAL → IDENTITY, INT → BIGINT, TIMESTAMP → TIMESTAMPTZ
ALTER TABLE links ALTER COLUMN id DROP DEFAULT;
ALTER TABLE links ALTER COLUMN id TYPE BIGINT;
ALTER TABLE links ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE links ALTER COLUMN project_id TYPE BIGINT;
ALTER TABLE links ALTER COLUMN created_at TYPE TIMESTAMPTZ;

-- optional fields: NOT NULL DEFAULT '' → NULL
UPDATE links SET title = NULL WHERE title = '';
ALTER TABLE links ALTER COLUMN title DROP DEFAULT;
ALTER TABLE links ALTER COLUMN title DROP NOT NULL;

UPDATE links SET description = NULL WHERE description = '';
ALTER TABLE links ALTER COLUMN description DROP DEFAULT;
ALTER TABLE links ALTER COLUMN description DROP NOT NULL;

UPDATE links SET og_image = NULL WHERE og_image = '';
ALTER TABLE links ALTER COLUMN og_image DROP DEFAULT;
ALTER TABLE links ALTER COLUMN og_image DROP NOT NULL;
